### ISSUE TITLE
[version 2.4.5] Question about "service method was called twice"

### ISSUE THREAD

**Issue by AlexDochioiu** [d-markey/squadron_builder#12]
Hello. Hope you don't mind me. 

I am looking at the latest commit https://github.com/d-markey/squadron_builder/commit/867ab4943b6d3d09026b1e4492f390483c39e35d and also at the built code before/after this release.

I actually fail to see how the service method was called twice in the previous version. Would you mind clarifying this for me please to see what am I missing?

**Comment by d-markey** [comment]
Yep, the original code was:

```dart
        return '${cmd.id}: ($req) async => ${cmd.serializedResult('(await $serviceCall)')}';
```

Now if the method is associated to a marshaller, and the return value is nullable (that's the key thing), the generated code would look like:

```dart
    $cmdId: ($req) async => ((await serviceMethod($req)) == null) ? null : marshal((await serviceMethod($req)),
```

I changed the code so the return value is stored in a variable before it gets marshalled.

**Comment by AlexDochioiu** [comment]
Ok, that explains it! The change log doesn't mention that this applies only to functions returning nullable (which use marshaller). When I looked in my code, I only checked some that were returning non-nullable types which is what caused my confusion.

Thank you for clarifying this!
