### ISSUE TITLE
Incorrect generated declarations when imports have a prefix

### ISSUE THREAD

**Issue by aci8** [d-markey/squadron_builder#14]
When import in service definition class file has a prefix generated files that used types from prefixed imports have incorrect declarations.

For example, if service definition code is
```dart
//...prefixed import
import 'dart:typed_data' as typed_data;

@SquadronService()
class TestPrefixedImportType {
  TestPrefixedImportType(this.typedData);

  typed_data.Int8List typedData; // Int8List from prefixed import

  @SquadronMethod()
  FutureOr<typed_data.Int8List?> getTypedData() => typedData;
}
```
The generated cod will be
```dart
/// Worker for TestPrefixedImportType
class TestPrefixedImportTypeWorker extends Worker
    implements TestPrefixedImportType {
  TestPrefixedImportTypeWorker(this.typedData,
      {PlatformWorkerHook? platformWorkerHook})
      : super($TestPrefixedImportTypeActivator,
            args: [typedData], platformWorkerHook: platformWorkerHook);

  @override
  Int8List typedData; // Int8List without necessary prefix

  @override
  Future<Int8List?> getTypedData() => // Int8List without necessary prefix
      send(_$TestPrefixedImportTypeWorkerService._$getTypedDataId, args: []);
}
```
which is incorrect.

**Comment by d-markey** [comment]
I'll look into that, will keep you posted. In the meantime, you can modify the generated code to make it work.

**Comment by d-markey** [comment]
Been working on this but for the next version of Squadron. It's unlikely I'll port this for older versions due to lack of time. I'll release new versions soon and you'll have to upgrade (there will be a few breaking changes).

**Comment by d-markey** [comment]
Version 6 is available, please refer to Squadron's changelog for breaking changes.
