### ISSUE TITLE
Missing an explicit required modifier

### ISSUE THREAD

**Issue by sabin26** [d-markey/squadron_builder#17]
For a given squadron service:

```dart
@SquadronService(baseUrl: '/services/storage', wasm: true)
class KeyValueService {
  KeyValueService({required this.path});

  final String path;

  @SquadronMethod()
  Future<void> clear() async {}
}
```

### Steps to Reproduce
`dart compile wasm key_value_service.web.g.dart -o key_value_service.web.g.dart.wasm`

### Error
The parameter 'path' can't have a value of 'null' because of its type 'String', but the implicit default value is 'null'.

### Solution
Try adding either an explicit non-'null' default value or the 'required' modifier.
  _$KeyValueServiceWorkerService({super.path}) : super();

![squadron_builder_bug](https://github.com/user-attachments/assets/ec67b507-3ba9-4ac5-b436-345287406780)

**Comment by d-markey** [comment]
Thanks for the report, fixed.
