### ISSUE TITLE
Generated File Location

### ISSUE THREAD

**Issue by tcf909** [d-markey/squadron_builder#2]
Hello,

I'm just starting to look at squadron as a serious contender for a fundamental part of our stack. The general architecture lines up with what we would like to see from a service thread model. Much better than the common offloading mindsets I see in other dart multi-thread libraries (ie compute() ).

One thing that immediately hit me when I started getting one of the demo applications setup was having the generated files intermingled with the source files.

Is there anyway to offload all generated files to a .generated folder or similar.

1) We would not typically commit these to repo
2) Makes cleaning easier
3) Keeps a multi hundred file project from being unbearable.

Suggestions?

Thanks

**Comment by d-markey** [comment]
Hello, the first thing that comes to mind is to exclude `*.dart` from version control. Now the working folders will be left with all the generated files so it could be reorganised eg with one folder per service.

Now the real good move would be to customizer the full name of the target files. The build package supports capture groups to do that, but it doesn't play well when multiple parts are generated. So I'll need to work around this and/or submit a PR to support multiple part files as targets. I'll try something but it might take some time before I come up with a solution. 

Thanks for the feedback BTW, glad you find squadron useful :-)

**Comment by d-markey** [comment]
Working on it: https://github.com/dart-lang/source_gen/pull/647

**Comment by tcf909** [comment]
Very nice!

Definitely some great potential in this package.

**Comment by d-markey** [comment]
FYI the pull request has been merged. Now waiting for the release of `source_gen` on pub.dev.

**Comment by d-markey** [comment]
`source_gen` 1.3.0 has been released, so here's the final fix.

I've also updated the example code to provide specific build options to generate the source code in a dedicated folder.

Closing this issue, feel free to reopen or comment if you need further help.
