### ISSUE TITLE
Issue in web referenced file

### ISSUE THREAD

**Issue by julienzarka** [d-markey/squadron_builder#24]
The web code generated for the activator should refer to a minified js file instead of js file - or at least test both.

https://github.com/d-markey/squadron_builder/blob/0fa8d38fa3217f5074fb62d0cee88fa0c8992593/lib/src/assets/worker_assets_activator_web.dart#L26

**Comment by d-markey** [comment]
The minification level depends on the options you pass to `dart compile js` when generating the JS code from your Dart code.

See `dart compile js -h -v` for more info. You should use "-O2" or above to produce minified JavaScript.

Alternatively, you can use a minifier of your choice provided you minify to `your_worker_file_name.web.g.dart.js`. So for instance your build script could be something like:

```sh
dart compile js your_worker_file_name.web.g.dart -o your_worker_file_name.web.g.dart.tmp.js
your_minifier your_worker_file_name.web.g.dart.tmp.js your_worker_file_name.web.g.dart.js
```

Currently Squadron builder does not allow custom extensions. The generated code will try to load workers from:

- `$baseUrl/your_worker_file_name.web.g.dart.js` for JavaScript workers
- `$baseUrl/your_worker_file_name.web.g.dart.wasm` for Web Assembly workers -- but note that when compiling to Web Assembly, a your_worker_file_name.web.g.dart.mjs` file is also generated. This will actually be the file used to load and compile the `wasm` file (`mjs` stands for Module JavaScript, not minified JavaScript -- see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#aside_%E2%80%94_.mjs_versus_.js).

where "baseUrl" is the argument passed to `SquadronService`. This URL must point to the actual folder where your compiled workers will be deployed in production. Recent versions of Squadron allow the use of a leading `~` character to represent the base URL of the calling program (eg `~/workers/xxx.js` will map to `/my-app/workers/xxx.js` if your Flutter app is deployed to `/my-app`).
