### ISSUE TITLE
Web Worker SharedArrayBuffer

### ISSUE THREAD

**Issue by tcf909** [d-markey/squadron_builder#3]
Out of curiosity, have you considered or explored using SharedArryBuffers in the Worker (web) implementation?

**Comment by d-markey** [comment]
Yes, I have looked into `ArrayBuffer` and `SharedArrayBuffer` but I ended up considering serialization a user concern. Using `SharedArrayBuffer` requires binary serialization and I didn't want to enforce such a strong constraint. It is also not available on native platforms, and would further complicate the internals of Squadron.

Squadron provides class `SquadronMarshaller<T, S>` to convert an instance of a user class T into an instance of S that can be transported across worker boundaries (so it can be a `SharedArrayBuffer`, or a bare `String` for instance). The data class T should be annotated with `SerializeWith` to provide the marshaller implementation (which may be different BTW between Web and native platforms) and squadron_builder will use the specified marshaller when communicating with the worker.
